"""
Data audit: descriptive checks on the raw dataset that inform feature-
engineering decisions downstream (e.g., "should we drop or flag outlier
coordinates", "what date range do we actually have to build rolling/forecast
windows over").

This module only *reports* — it never mutates or drops rows. Decisions made
from these numbers are recorded in DECISIONS.md, not silently baked in here.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any

import pandas as pd

from app.ingestion.schema import LAT_RANGE, LON_RANGE


@dataclass
class DataAuditReport:
    total_rows: int = 0
    duplicate_full_rows: int = 0
    duplicate_ids: int = 0
    duplicate_vehicle_timestamp_pairs: int = 0

    min_created_datetime: str | None = None
    max_created_datetime: str | None = None
    monthly_distribution: dict[str, int] = field(default_factory=dict)

    missing_datetime_counts: dict[str, int] = field(default_factory=dict)

    coords_missing: int = 0
    coords_zero_zero: int = 0
    coords_out_of_bengaluru_bbox: int = 0
    coords_exact_duplicate_pairs: int = 0

    validation_status_counts: dict[str, int] = field(default_factory=dict)
    validation_status_missing: int = 0

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    def to_markdown(self) -> str:
        lines = [
            "# Data Quality Report",
            "",
            "Generated by `backend/app/ingestion/data_audit.py` against the raw dataset.",
            "This report is descriptive only — see `DECISIONS.md` for what we did about it.",
            "",
            "## Volume",
            f"- Total rows: **{self.total_rows:,}**",
            f"- Fully duplicate rows (all columns identical): **{self.duplicate_full_rows:,}**",
            f"- Duplicate `id` values: **{self.duplicate_ids:,}**",
            f"- Duplicate (vehicle_number, created_datetime) pairs (possible double-logging): **{self.duplicate_vehicle_timestamp_pairs:,}**",
            "",
            "## Date Range",
            f"- Earliest `created_datetime`: **{self.min_created_datetime}**",
            f"- Latest `created_datetime`: **{self.max_created_datetime}**",
            "",
            "### Monthly distribution (row count)",
            "| Month | Rows |",
            "|---|---|",
        ]
        for month, count in sorted(self.monthly_distribution.items()):
            lines.append(f"| {month} | {count:,} |")

        lines += [
            "",
            "## Missing Datetime Fields",
            "| Column | Missing (NaT) count |",
            "|---|---|",
        ]
        for col, count in self.missing_datetime_counts.items():
            lines.append(f"| {col} | {count:,} |")

        lines += [
            "",
            "## Coordinate Quality",
            f"- Missing lat/lon: **{self.coords_missing:,}**",
            f"- Exactly (0, 0) (likely bad GPS fix): **{self.coords_zero_zero:,}**",
            f"- Outside Bengaluru bounding box ({LAT_RANGE[0]}-{LAT_RANGE[1]}°N, {LON_RANGE[0]}-{LON_RANGE[1]}°E): **{self.coords_out_of_bengaluru_bbox:,}**",
            f"- Exact-duplicate (lat, lon) pairs shared by >1 row (rounding/device artifacts): **{self.coords_exact_duplicate_pairs:,}**",
            "",
            "## Validation Status",
            "| Status | Count |",
            "|---|---|",
        ]
        for status, count in self.validation_status_counts.items():
            lines.append(f"| {status} | {count:,} |")
        lines.append(f"| (missing) | {self.validation_status_missing:,} |")

        return "\n".join(lines) + "\n"


def run_audit(df: pd.DataFrame) -> DataAuditReport:
    report = DataAuditReport(total_rows=len(df))

    # --- Duplicates ---
    report.duplicate_full_rows = int(df.duplicated(keep=False).sum())
    report.duplicate_ids = int(df["id"].duplicated(keep=False).sum())
    if "vehicle_number" in df.columns:
        vt = df.dropna(subset=["vehicle_number", "created_datetime"])
        report.duplicate_vehicle_timestamp_pairs = int(
            vt.duplicated(subset=["vehicle_number", "created_datetime"], keep=False).sum()
        )

    # --- Date range / monthly distribution ---
    created = df["created_datetime"].dropna()
    if len(created):
        report.min_created_datetime = str(created.min())
        report.max_created_datetime = str(created.max())
        monthly = created.dt.to_period("M").value_counts().sort_index()
        report.monthly_distribution = {str(k): int(v) for k, v in monthly.items()}

    # --- Missing datetimes ---
    for col in ["created_datetime", "closed_datetime", "modified_datetime",
                "action_taken_timestamp", "data_sent_to_scita_timestamp", "validation_timestamp"]:
        if col in df.columns:
            report.missing_datetime_counts[col] = int(df[col].isna().sum())

    # --- Coordinate quality ---
    report.coords_missing = int(df["latitude"].isna().sum() | df["longitude"].isna().sum())
    report.coords_zero_zero = int(((df["latitude"] == 0) & (df["longitude"] == 0)).sum())
    lat_ok = df["latitude"].between(*LAT_RANGE)
    lon_ok = df["longitude"].between(*LON_RANGE)
    report.coords_out_of_bengaluru_bbox = int((~(lat_ok & lon_ok)).sum())
    coord_pairs = df.dropna(subset=["latitude", "longitude"])
    report.coords_exact_duplicate_pairs = int(
        coord_pairs.duplicated(subset=["latitude", "longitude"], keep=False).sum()
    )

    # --- Validation status ---
    if "validation_status" in df.columns:
        counts = df["validation_status"].value_counts(dropna=True)
        report.validation_status_counts = {str(k): int(v) for k, v in counts.items()}
        report.validation_status_missing = int(df["validation_status"].isna().sum())

    return report


def save_report(report: DataAuditReport, out_dir: Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "data_quality_report.md").write_text(report.to_markdown(), encoding="utf-8")
    (out_dir / "data_quality_report.json").write_text(
        json.dumps(report.to_dict(), indent=2), encoding="utf-8"
    )


if __name__ == "__main__":
    from app.core.config import settings
    from app.ingestion.load_data import load_raw_violations

    df = load_raw_violations()
    rpt = run_audit(df)
    print(rpt.to_markdown())
    docs_dir = settings.raw_data_full_path.parents[2] / "docs"
    save_report(rpt, docs_dir)
    print(f"\nSaved to {docs_dir / 'data_quality_report.md'}")
